console.log("Hello Winc Academy");
            let myName = 'Cees';
            console.log(myName);
            let eersteGetal = 5;
            let tweedeGetal = 7;
            console.log (eersteGetal + tweedeGetal);
            let myLastName ='Klap';
            console.log (myName + myLastName);
            console.log (tweedeGetal - eersteGetal);
            console.log (tweedeGetal * eersteGetal);
            console.log (tweedeGetal / eersteGetal);
            console.log (tweedeGetal % eersteGetal);
            let leeftijd = 18;
            console.log (typeof leeftijd);